### PR TITLE
Button events

### PR DESCRIPTION
**Pull request by clayrisser**
I also added `npm run bootstrap`. It seems much cleaner than `node ./node_modules/lerna/bin/learna bootstrap`.

Since gtk doesn't have functions for calling buttons signals other than signal_clicked, there's not really a clear way to test the other button events.

### CODE REVIEW

**Comment by jamrizzi** [comment]
I also added npm run bootstrap. It seems much cleaner than node ./node_modules/lerna/bin/learna bootstrap.

Since gtk doesn't have functions for calling buttons signals other than signal_clicked, there's not really a clear way to test the other button events.

**Comment by Place1** [comment]
Is it ok if we don't include the `package.json` changes? I've added all the scripts in 
#6

**Comment by Place1** [comment]
i'm curious about how we can write tests for these things? I found that, for Button, there's a `button.clicked()` method that will simulate the button being clicked. Does this exist for other event's? If so we could use that to write tests. If not, how can we write tests?

I see testing as a major milestone for this initial part of the project. I really want to nail this down before we start adding lots of bindings (similar to #7)

**Comment by clayrisser** [comment]
It does not exist for other events. I thought maybe `button.clicked()` would run the pressed and released signals, but it doesn't.

**Comment by Place1** [comment]
I guess we’ll have to do some research.

**Comment by Place1** [comment]
I'm closing this because with the project restructure to use `node-gir` it's no longer relevant.

**Pull request closed without merging**
